language: go
dist: bionic
go:
  - "1.14"
  - master
install:
  - cd $HOME; git clone https://github.com/guanzhi/GmSSL.git; cd GmSSL
  - ./config
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - cd gmssl; go build; cd -
script:
  - cd test; go test;