language: go
dist: bionic
os:
  - osx
  - linux
go:
  - "1.14"
  - "1.12"
  - master
install:
  - cd $HOME; git clone https://github.com/guanzhi/GmSSL.git; cd GmSSL
  - ./config
  - make
  - sudo make install_sw
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
  - cd gmssl; go build; cd -
script:
  - curl --version # test curl affection
  - cd test; go test;
