name: github workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/#0_0_*_*_0
jobs:
  buildNtest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        with:
          repository: guanzhi/GmSSL
          path: GMSSL
      - run: SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl;
        working-directory: GMSSL
      - run: make
        working-directory: GMSSL
      - run: sudo make install_sw
        working-directory: GMSSL
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.16
      - run: go build
        working-directory: gmssl
      - run: curl --version
        name: curl san check
      - run: env LD_LIBRARY_PATH=/usr/local/gmssl/lib go test -v ./...
        working-directory: test
      - run: env LD_LIBRARY_PATH=/usr/local/gmssl/lib go test -bench=. -run=none -cover
        working-directory: test
        name: bench test
