name: github workflow
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/#0_0_*_*_0
env:
  LD_LIBRARY_PATH: /usr/local/gmssl/lib
jobs:
  buildNtest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        with:
          repository: guanzhi/GmSSL
          path: GMSSL
          ref: master
      - run: SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl;
        working-directory: GMSSL
      - run: make
        working-directory: GMSSL
      - run: sudo make install_sw
        working-directory: GMSSL
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - run: go build
        working-directory: gmssl
      - run: go test -v ./...
        working-directory: test
      - run: go test -bench=. -run=none -cover
        working-directory: test
        name: bench test
